/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_Stack */

#ifndef _Included_io_opentimeline_opentimelineio_Stack
#define _Included_io_opentimeline_opentimelineio_Stack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_Stack
 * Method:    initialize
 * Signature: (Ljava/lang/String;Lio/opentimeline/opentime/TimeRange;Lio/opentimeline/opentimelineio/AnyDictionary;[Lio/opentimeline/opentimelineio/Effect;[Lio/opentimeline/opentimelineio/Marker;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Stack_initialize
  (JNIEnv *, jobject, jstring, jobject, jobject, jobjectArray, jobjectArray);

/*
 * Class:     io_opentimeline_opentimelineio_Stack
 * Method:    rangeOfChildAtIndex
 * Signature: (I)Lio/opentimeline/opentime/TimeRange;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Stack_rangeOfChildAtIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_Stack
 * Method:    trimmedRangeOfChildAtIndex
 * Signature: (I)Lio/opentimeline/opentime/TimeRange;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Stack_trimmedRangeOfChildAtIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_Stack
 * Method:    getAvailableRange
 * Signature: ()Lio/opentimeline/opentime/TimeRange;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Stack_getAvailableRange
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Stack
 * Method:    getRangeOfAllChildren
 * Signature: ()Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Stack_getRangeOfAllChildren
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Stack
 * Method:    clipIfNative
 * Signature: (Ljava/util/Optional;Z)[Lio/opentimeline/opentimelineio/Clip;
 */
JNIEXPORT jobjectArray JNICALL Java_io_opentimeline_opentimelineio_Stack_clipIfNative
  (JNIEnv *, jobject, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
